myquote/buyers/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import (BuyersListView, BuyersCreateView, BuyersUpdateView, BuyersDeleteView)

urlpatterns = [
    path('', login_required(BuyersListView.as_view()), name="buyers-list"),
    path('create/', login_required(BuyersCreateView.as_view()), name="buyers-create"),
    path('update/<int:pk>/', login_required(BuyersUpdateView.as_view()), name="buyers-update"),
    path('delete/<int:pk>/', login_required(BuyersDeleteView.as_view()), name="buyers-delete"),

]

myquote/myquote/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('buyers/', include('buyers.urls')),
    path('products/', include('products.urls')),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    path('accounts/', include('accounts.urls')),
    path("sellers/", include("seller.urls")),
    path('about/', TemplateView.as_view(template_name="about.html"), name='about'),
    #path('aboutt/', TemplateView.as_view(template_name="aboutt.html"), name='aboutt'),
    path('configuration/', include('configuration.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myquote/seller/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import *
from .models import Seller

urlpatterns = [
    path('', sellers_list, name="sellers_list"),
    path('create/', create_seller, name="create_seller"),
    path('<int:id>/', seller, name="seller"),
    path('<int:id_code>/update/', update_seller, name="update_seller"),
    path('<int:id_code>/delete/', delete_seller, name="delete_seller"),
]

myquote/seller/models.py
from django.contrib.auth.models import User
from django.db import models


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="seller")
    id_code = models.CharField(max_length=50, blank=True, null=True)
    phone_number = models.BigIntegerField(unique=True)
    dt_entrance = models.TextField(blank=True, null=True)

    def __str__(self):
        return "{} ({})".format(self.user, self.id_code)

myquote/myquote/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=45)
    email = forms.EmailField(label='Email', max_length=45, required=True)
    city = forms.CharField(label='City', max_length=45)
    CHOICES = [
        ('Support', 'Support'),
        ('Financial', 'Financial'),
        ('Others', 'Others')
    ]
    subject = forms.ChoiceField(label='Subject', choices=CHOICES, required=True)
    message = forms.CharField(label='Message', max_length=1024)

    def clean(self):
        super(ContactForm, self).clean()

        name = self.cleaned_data.get('name')
        email = self.cleaned_data.get('email')
        city = self.cleaned_data.get('city')
        message = self.cleaned_data.get('message')

        if len(name) > 45:
            self._errors['name'] = self.error_class([
                'Maximum 45 characters allowed.'
            ])
        if len(email) > 45:
            self._errors['email'] = self.error_class([
                'Maximum 45 characters allowed.'
            ])
        if len(city) > 45:
            self._errors['city'] = self.error_class([
                'Maximum 45 characters allowed.'
            ])
        if len(message) > 1024:
            self._errors['message'] = self.error_class([
                'Maximum 45 characters allowed.'
            ])

        return self.cleaned_data

myquote/seller/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Seller


def create_seller(request):
    if request.method == "GET":
        return render(request, "create_seller.html")
    else:
        try:
            seller = Seller(name=request.POST['name'],
                            email=request.POST['email'],
                            phone_number=request.POST['phonenumber'],
                            dt_entrance=request.POST['dt_entrance'])
            seller.save()
            return render(request, "create_seller.html", {"message": f"Seller {request.POST['name']} added."})
        except ValueError:
            return render(request, "create_seller.html", {"ERROR": "Bad data provided!"})


def sellers_list(request):
    sellers = Seller.objects.all()
    return render(request, "seller_list.html", {"sellers": sellers})


def seller(request, id):
    seller = get_object_or_404(Seller, id_code=id)
    return render(request, "seller.html", {"seller": seller})


def update_seller(request, id_code):
    if request.method == "POST":
        seller = get_object_or_404(Seller, id_code=id_code)
        try:
            seller.name = request.POST['name']
            seller.email = request.POST['email']
            seller.phone_number = request.POST['phonenumber']
            seller.dt_entrance = request.POST['dt_entrance']
            seller.save()
            return render(request, "seller.html", {"seller": seller, "message": "Data updated"})
        except ValueError:
            return render(request, "seller.html", {"seller": seller, "ERROR": "Bad data provided!"})


def delete_seller(request, id_code):
    if request.method == "POST":
        seller = get_object_or_404(Seller, id_code=id_code)
        seller.delete()
    return redirect("sellers_list")

myquote/seller/templates/create_seller.html
{% extends 'base.html' %}

{% block title %}
    Create seller
{% endblock %}

{% block content %}
    <div class="container text-center lead">
        <div class="display-4 mt-4 mb-4">CREATE NEW SELLER</div>
        {% if message %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
        {% endif %}
        {% if ERROR %}
            <div class="alert alert-danger" role="alert">{{ ERROR }}‹</div>
        {% endif %}
        <form method="POST" class="rounded pt-3 shadow-lg">
            {% csrf_token %}
            <fieldset class="form-group d-flex pl-5 ml-5 mr-5 pr-5">
                <div class="form-group lead">
                    <label for="id_name">Name</label>
                    <br>
                    <input name="name" id="id_name" type="text">
                    <br>

                    <label for="id_email">Email</label>
                    <br>
                    <input type="email"  name="email" id="id_email">
                    <br>

                    <label for="id_phone_number">Phonenumber</label>
                    <br>
                    <input name="phonenumber" type="text" id="id_phone_number">
                    <br>

                    <label for="id_dt_entrance">Data about seller</label>
                    <br>
                    <input name="dt_entrance" type="text" id="id_dt_entrance">
                </div>
            </fieldset>
            <button type="submit">Submit</button>
        </form>
    </div>

{% endblock %}

myquote/seller/templates/delete_seller.html
{% extends "base.html" %}

{% block title %}
{% endblock %}

{% block content %}
{% endblock %}

myquote/seller/templates/seller.html
{% extends 'base.html' %}

{% block content %}
    <div class="container text-center lead">
        {% if message %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endif %}
        {% if ERROR %}
        <div class="alert alert-danger" role="alert">
            {{ ERROR }}
        </div>
        {% endif %}

        <div class="rounded pt-3 shadow-lg">
            <form method="POST" action="{% url 'update_seller' seller.id_code %}">
                {% csrf_token %}

                    <fieldset class="form-group d-flex pl-5 ml-5 mr-5 pr-5">
                        <div class="form-group lead">
                            <label for="id_name">name</label><br>
                            <input name="name" id="id_name" type="text" value="{{ seller.name }}">
                            <br>

                            <label for="id_email">email</label><br>
                            <input type="email"  name="email" id="id_email" value="{{ seller.email }}">
                            <br>

                            <label for="id_phone_number">Phonenumber</label><br>
                            <input name="phonenumber" type="text" id="id_phone_number" value="{{ seller.phone_number }}">
                            <br>

                            <label for="id_dt_entrance">Data about seller</label><br>
                            <input name="dt_entrance" type="text" id="id_dt_entrance" value="{{ seller.dt_entrance }}">
                            <br>
                        </div>
                    </fieldset>
                <button type="submit" class="btn btn-warning">Update</button>

            </form>

            <form method="POST" action="{% url 'delete_seller' seller.id_code %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </div>

{% endblock %}

myquote/seller/templates/seller_list.html
{% extends 'base.html' %}

{% block title %}Sellers{% endblock %}

{% block content %}
    <div class="container text-center lead">
        <div class="display-4 mt-4 mb-4">Sellers</div>
        <form action="{% url "create_seller" %}">
            <button type="submit" class="btn btn-default">Create seller</button>
        </form>
        <br>
        <ul>
            {% for seller in sellers %}
                <div class="shadow-sm p-3 mb-5 bg-white rounded">
                <a href="{% url 'seller' seller.id_code %}">
                <li class="list-group-item">Name:{{seller.name}}</li>
                <li class="list-group-item">Enamil: {{seller.email}}</li>
                <li class="list-group-item">Phone: {{ seller.phone_number }}</li>
                <li class="list-group-item">Data: {{ seller.dt_entrance }}</li>
                </a>
                </div>
                <br>

            {% endfor %}
        </ul>
    </div>
{% endblock %}